spring:
  application:
    name: invoice-manager
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
invoice:
  limit: 200

